/**
 * M-PESEWA CORE APPLICATION
 * Main Application Entry Point
 * Strict Hierarchy: Global → Countries → Groups → Lenders → Borrowers (Ledgers)
 */

class MPesewaApp {
    constructor() {
        this.version = '1.0.0';
        this.env = this.getEnvironment();
        this.state = this.initializeState();
        this.countries = this.initializeCountries();
        this.hierarchy = this.initializeHierarchy();
        this.subscriptions = this.initializeSubscriptions();
        this.ledgers = this.initializeLedgers();
        this.blacklist = this.initializeBlacklist();
        
        console.log(`M-Pesewa v${this.version} initialized in ${this.env} mode`);
    }
    
    /**
     * STRICT CORE HIERARCHY (MANDATORY)
     * Global → Countries (12) → Groups → Lenders → Borrowers (Ledgers)
     */
    initializeHierarchy() {
        return {
            level: 'Global',
            children: {
                countries: {
                    level: 'Country',
                    rules: {
                        isolation: true,
                        noCrossCountryTransactions: true,
                        currencyLocked: true,
                        maxCountries: 12
                    },
                    list: [
                        'Kenya', 'Uganda', 'Tanzania', 'Rwanda', 'DRC',
                        'Burundi', 'Nigeria', 'Ghana', 'South Sudan',
                        'Somalia', 'South Africa', 'Ethiopia'
                    ]
                },
                groups: {
                    level: 'Group',
                    rules: {
                        minMembers: 5,
                        maxMembers: 1000,
                        countryLocked: true,
                        invitationOnly: true,
                        maxGroupsPerUser: 4,
                        maxGroupsPerCountry: 'unlimited'
                    }
                },
                lenders: {
                    level: 'Lender',
                    rules: {
                        requiresSubscription: true,
                        subscriptionExpiry: '28th of each month',
                        canOnlyLendWithinGroup: true,
                        unlimitedLedgers: true,
                        tierLimits: {
                            Basic: 1500,
                            Premium: 5000,
                            Super: 20000,
                            'Lender of Lenders': 50000
                        }
                    }
                },
                borrowers: {
                    level: 'Borrower',
                    rules: {
                        noSubscriptionFees: true,
                        maxGroups: 4,
                        requiresGoodRatingForMultipleGroups: true,
                        loanTerms: {
                            duration: '7 days',
                            interest: '10%',
                            dailyPartialRepayments: true,
                            penaltyAfter7Days: '5% daily',
                            defaultAfter: '2 months'
                        }
                    }
                },
                ledgers: {
                    level: 'Ledger',
                    rules: {
                        autoGeneratedOnApproval: true,
                        unlimitedPerLender: true,
                        oneLedgerPerBorrower: true,
                        manualUpdates: true,
                        adminOverride: true
                    }
                }
            }
        };
    }
    
    getEnvironment() {
        const hostname = window.location.hostname;
        if (hostname.includes('localhost') || hostname.includes('127.0.0.1')) {
            return 'development';
        }
        if (hostname.includes('github.io')) {
            return 'production';
        }
        return 'production';
    }
    
    initializeState() {
        return {
            user: null,
            country: null,
            group: null,
            role: null,
            subscription: null,
            isAuthenticated: false,
            isLender: false,
            isBorrower: false,
            isAdmin: false,
            sessionStart: new Date(),
            lastActivity: new Date(),
            offline: !navigator.onLine
        };
    }
    
    initializeCountries() {
        return {
            Kenya: {
                code: 'KE',
                currency: 'KSh',
                symbol: 'KSh',
                contact: '+254 709 219 000',
                flag: '🇰🇪',
                timezone: 'Africa/Nairobi',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Uganda: {
                code: 'UG',
                currency: 'UGX',
                symbol: 'UGX',
                contact: '+256 392 175 546',
                flag: '🇺🇬',
                timezone: 'Africa/Kampala',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Tanzania: {
                code: 'TZ',
                currency: 'TZS',
                symbol: 'TZS',
                contact: '+255 659 073 010',
                flag: '🇹🇿',
                timezone: 'Africa/Dar_es_Salaam',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Rwanda: {
                code: 'RW',
                currency: 'RWF',
                symbol: 'RWF',
                contact: '+250 791 590 801',
                flag: '🇷🇼',
                timezone: 'Africa/Kigali',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            DRC: {
                code: 'CD',
                currency: 'CDF',
                symbol: 'CDF',
                contact: '+243 81 000 0000',
                flag: '🇨🇩',
                timezone: 'Africa/Kinshasa',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Burundi: {
                code: 'BI',
                currency: 'BIF',
                symbol: 'BIF',
                contact: '+257 79 000 000',
                flag: '🇧🇮',
                timezone: 'Africa/Bujumbura',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Nigeria: {
                code: 'NG',
                currency: 'NGN',
                symbol: '₦',
                contact: '+234 800 000 0000',
                flag: '🇳🇬',
                timezone: 'Africa/Lagos',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Ghana: {
                code: 'GH',
                currency: 'GHS',
                symbol: 'GH₵',
                contact: '+233 24 000 0000',
                flag: '🇬🇭',
                timezone: 'Africa/Accra',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            'South Sudan': {
                code: 'SS',
                currency: 'SSP',
                symbol: 'SSP',
                contact: '+211 955 000 000',
                flag: '🇸🇸',
                timezone: 'Africa/Juba',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Somalia: {
                code: 'SO',
                currency: 'SOS',
                symbol: 'SOS',
                contact: '+252 63 0000000',
                flag: '🇸🇴',
                timezone: 'Africa/Mogadishu',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            'South Africa': {
                code: 'ZA',
                currency: 'ZAR',
                symbol: 'R',
                contact: '+27 11 000 0000',
                flag: '🇿🇦',
                timezone: 'Africa/Johannesburg',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            },
            Ethiopia: {
                code: 'ET',
                currency: 'ETB',
                symbol: 'ETB',
                contact: '+251 11 000 0000',
                flag: '🇪🇹',
                timezone: 'Africa/Addis_Ababa',
                rules: {
                    isolation: true,
                    localCurrencyOnly: true,
                    localRegulations: true
                }
            }
        };
    }
    
    initializeSubscriptions() {
        return {
            Basic: {
                maxPerWeek: 1500,
                monthly: 50,
                biAnnual: 250,
                annual: 500,
                crbRequired: false,
                maxLedgers: 1500,
                description: 'Basic lending tier'
            },
            Premium: {
                maxPerWeek: 5000,
                monthly: 250,
                biAnnual: 1500,
                annual: 2500,
                crbRequired: false,
                maxLedgers: 10000,
                description: 'Premium lending tier'
            },
            Super: {
                maxPerWeek: 20000,
                monthly: 1000,
                biAnnual: 5000,
                annual: 8500,
                crbRequired: true,
                maxLedgers: 20000,
                description: 'Super lending tier'
            },
            'Lender of Lenders': {
                maxPerWeek: 50000,
                monthly: 500,
                biAnnual: 3500,
                annual: 6500,
                crbRequired: true,
                maxLedgers: 'unlimited',
                description: 'Lender of lenders tier',
                customTerms: true
            }
        };
    }
    
    initializeLedgers() {
        return {
            fields: [
                'borrowerName',
                'borrowerContact',
                'borrowerLocation',
                'guarantor1',
                'guarantor2',
                'loanCategory',
                'amountBorrowed',
                'dateBorrowed',
                'dueDate',
                'interest',
                'penalty',
                'amountOverdue',
                'status',
                'lenderId',
                'groupId',
                'countryCode'
            ],
            statuses: ['Active', 'Cleared', 'Defaulted', 'Disputed'],
            interestRate: 0.10, // 10%
            penaltyRate: 0.05, // 5% daily after 7 days
            defaultAfterDays: 60 // 2 months
        };
    }
    
    initializeBlacklist() {
        return {
            criteria: {
                defaultAfterDays: 60,
                requiresFullRepayment: true,
                adminRemovalOnly: true,
                platformWideVisibility: true
            },
            restrictions: {
                cannotBorrow: true,
                cannotJoinNewGroups: true,
                visibleToAllLenders: true
            }
        };
    }
    
    // Country Operations
    setCountry(countryName) {
        if (!this.countries[countryName]) {
            throw new Error(`Invalid country: ${countryName}. Must be one of: ${Object.keys(this.countries).join(', ')}`);
        }
        
        this.state.country = countryName;
        this.state.currency = this.countries[countryName].currency;
        localStorage.setItem('mpesewa_country', countryName);
        
        console.log(`Country set to: ${countryName} (${this.countries[countryName].currency})`);
        return this.countries[countryName];
    }
    
    getCountry() {
        return this.state.country ? this.countries[this.state.country] : null;
    }
    
    getAllCountries() {
        return Object.keys(this.countries).map(name => ({
            name,
            ...this.countries[name]
        }));
    }
    
    // Group Operations
    createGroup(groupName, groupType, country) {
        if (!country) country = this.state.country;
        if (!country) throw new Error('Country must be set before creating a group');
        
        const group = {
            id: `group_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
            name: groupName,
            type: groupType,
            country: country,
            members: [],
            lenders: [],
            borrowers: [],
            createdAt: new Date(),
            admin: this.state.user?.id || null,
            rules: {
                isolation: true,
                maxMembers: 1000,
                minMembers: 5,
                countryLocked: true
            }
        };
        
        console.log(`Group created: ${groupName} in ${country}`);
        return group;
    }
    
    // User Operations
    registerUser(userData) {
        const { role, country, group, subscription } = userData;
        
        // Validate country
        if (!this.countries[country]) {
            throw new Error(`Invalid country: ${country}`);
        }
        
        // Validate role
        if (!['lender', 'borrower', 'both'].includes(role)) {
            throw new Error('Role must be lender, borrower, or both');
        }
        
        // Validate subscription for lenders
        if (role === 'lender' || role === 'both') {
            if (!subscription) {
                throw new Error('Lenders must select a subscription tier');
            }
            if (!this.subscriptions[subscription]) {
                throw new Error(`Invalid subscription tier: ${subscription}`);
            }
        }
        
        const user = {
            id: `user_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
            ...userData,
            registrationDate: new Date(),
            rating: 5,
            status: 'active',
            isBlacklisted: false,
            groups: [],
            ledgers: []
        };
        
        this.state.user = user;
        this.state.isAuthenticated = true;
        this.state.role = role;
        this.state.country = country;
        
        if (role === 'lender' || role === 'both') {
            this.state.isLender = true;
            this.state.subscription = subscription;
        }
        
        if (role === 'borrower' || role === 'both') {
            this.state.isBorrower = true;
        }
        
        // Store in localStorage
        localStorage.setItem('mpesewa_user', JSON.stringify(user));
        localStorage.setItem('mpesewa_auth', 'true');
        
        console.log(`User registered: ${userData.username} as ${role} in ${country}`);
        return user;
    }
    
    login(username, password) {
        // In a real app, this would be an API call
        const storedUser = localStorage.getItem('mpesewa_user');
        if (storedUser) {
            const user = JSON.parse(storedUser);
            // Simple validation (in production, use proper auth)
            if (user.username === username) {
                this.state.user = user;
                this.state.isAuthenticated = true;
                this.state.role = user.role;
                this.state.country = user.country;
                
                if (user.role === 'lender' || user.role === 'both') {
                    this.state.isLender = true;
                }
                if (user.role === 'borrower' || user.role === 'both') {
                    this.state.isBorrower = true;
                }
                
                console.log(`User logged in: ${username}`);
                return user;
            }
        }
        
        throw new Error('Invalid credentials');
    }
    
    logout() {
        this.state.user = null;
        this.state.isAuthenticated = false;
        this.state.isLender = false;
        this.state.isBorrower = false;
        this.state.isAdmin = false;
        this.state.country = null;
        this.state.group = null;
        this.state.subscription = null;
        
        localStorage.removeItem('mpesewa_user');
        localStorage.removeItem('mpesewa_auth');
        
        console.log('User logged out');
    }
    
    // Loan Operations
    calculateLoan(amount, days = 7) {
        const interest = amount * this.ledgers.interestRate;
        const totalRepayment = amount + interest;
        
        let penalty = 0;
        if (days > 7) {
            const extraDays = days - 7;
            penalty = amount * this.ledgers.penaltyRate * extraDays;
        }
        
        return {
            principal: amount,
            interest: interest,
            total: totalRepayment + penalty,
            dailyRepayment: (totalRepayment + penalty) / days,
            breakdown: {
                principal: amount,
                interest: interest,
                penalty: penalty,
                total: totalRepayment + penalty
            }
        };
    }
    
    // Subscription Operations
    checkSubscriptionStatus() {
        if (!this.state.subscription || !this.state.user) {
            return { active: false, message: 'No subscription found' };
        }
        
        const today = new Date();
        const expiryDate = this.calculateSubscriptionExpiry();
        
        const isActive = today <= expiryDate;
        const daysRemaining = Math.ceil((expiryDate - today) / (1000 * 60 * 60 * 24));
        
        return {
            active: isActive,
            expiryDate: expiryDate,
            daysRemaining: daysRemaining,
            tier: this.state.subscription,
            limits: this.subscriptions[this.state.subscription]
        };
    }
    
    calculateSubscriptionExpiry() {
        const today = new Date();
        const currentMonth = today.getMonth();
        const currentYear = today.getFullYear();
        
        // Subscription expires on 28th of each month
        let expiryDate = new Date(currentYear, currentMonth, 28);
        
        // If today is past the 28th, set to 28th of next month
        if (today.getDate() > 28) {
            expiryDate = new Date(currentYear, currentMonth + 1, 28);
        }
        
        return expiryDate;
    }
    
    // Validation Methods
    validateBorrowerForLoan(borrowerId, amount, groupId) {
        const borrower = this.getUserById(borrowerId);
        if (!borrower) {
            return { valid: false, error: 'Borrower not found' };
        }
        
        if (borrower.isBlacklisted) {
            return { valid: false, error: 'Borrower is blacklisted' };
        }
        
        if (borrower.rating < 3) {
            return { valid: false, error: 'Borrower rating too low' };
        }
        
        // Check if borrower is in the group
        if (!borrower.groups.includes(groupId)) {
            return { valid: false, error: 'Borrower not in specified group' };
        }
        
        // Check active loans in this group
        const activeLoans = this.getActiveLoans(borrowerId, groupId);
        if (activeLoans.length > 0) {
            return { valid: false, error: 'Borrower has active loan in this group' };
        }
        
        return { valid: true, borrower };
    }
    
    validateLenderForLoan(lenderId, amount, subscriptionTier) {
        const lender = this.getUserById(lenderId);
        if (!lender) {
            return { valid: false, error: 'Lender not found' };
        }
        
        const subscription = this.checkSubscriptionStatus();
        if (!subscription.active) {
            return { valid: false, error: 'Lender subscription expired' };
        }
        
        const tierLimit = this.subscriptions[subscriptionTier]?.maxPerWeek || 0;
        if (amount > tierLimit) {
            return { valid: false, error: `Amount exceeds tier limit (${tierLimit})` };
        }
        
        return { valid: true, lender, subscription };
    }
    
    // Helper Methods
    getUserById(userId) {
        // In production, this would query a database
        return this.state.user?.id === userId ? this.state.user : null;
    }
    
    getActiveLoans(userId, groupId) {
        // In production, this would query a database
        return [];
    }
    
    // Event Handlers
    handleOnlineStatus() {
        this.state.offline = !navigator.onLine;
        if (navigator.onLine) {
            this.syncPendingOperations();
        }
    }
    
    syncPendingOperations() {
        // Sync any pending operations when coming online
        console.log('Syncing pending operations...');
        // Implementation would sync with backend
    }
    
    // Error Handling
    handleError(error, context = '') {
        console.error(`M-Pesewa Error [${context}]:`, error);
        
        // Report to error tracking service in production
        if (this.env === 'production') {
            // Send error to analytics
        }
        
        return {
            error: true,
            message: error.message,
            context,
            timestamp: new Date()
        };
    }
    
    // Lifecycle Methods
    start() {
        console.log('M-Pesewa application starting...');
        
        // Set up event listeners
        window.addEventListener('online', () => this.handleOnlineStatus());
        window.addEventListener('offline', () => this.handleOnlineStatus());
        
        // Initialize from localStorage
        this.restoreFromStorage();
        
        // Check PWA installation
        this.checkPWAInstallation();
        
        console.log('M-Pesewa application started successfully');
    }
    
    restoreFromStorage() {
        const auth = localStorage.getItem('mpesewa_auth');
        const user = localStorage.getItem('mpesewa_user');
        const country = localStorage.getItem('mpesewa_country');
        
        if (auth === 'true' && user) {
            try {
                const userData = JSON.parse(user);
                this.state.user = userData;
                this.state.isAuthenticated = true;
                this.state.role = userData.role;
                
                if (userData.role === 'lender' || userData.role === 'both') {
                    this.state.isLender = true;
                }
                if (userData.role === 'borrower' || userData.role === 'both') {
                    this.state.isBorrower = true;
                }
            } catch (error) {
                console.error('Error restoring user from storage:', error);
            }
        }
        
        if (country && this.countries[country]) {
            this.state.country = country;
        }
    }
    
    checkPWAInstallation() {
        if ('serviceWorker' in navigator && 'PushManager' in window) {
            console.log('PWA capabilities detected');
            this.state.pwaSupported = true;
        }
    }
    
    stop() {
        console.log('M-Pesewa application stopping...');
        
        // Clean up event listeners
        window.removeEventListener('online', () => this.handleOnlineStatus());
        window.removeEventListener('offline', () => this.handleOnlineStatus());
        
        // Save state
        this.saveToStorage();
        
        console.log('M-Pesewa application stopped');
    }
    
    saveToStorage() {
        if (this.state.user) {
            localStorage.setItem('mpesewa_user', JSON.stringify(this.state.user));
        }
        if (this.state.country) {
            localStorage.setItem('mpesewa_country', this.state.country);
        }
    }
    
    // Debug Methods
    debug() {
        return {
            app: {
                version: this.version,
                env: this.env,
                state: this.state
            },
            hierarchy: this.hierarchy,
            countries: this.getAllCountries(),
            subscriptions: this.subscriptions,
            user: this.state.user
        };
    }
}

// Create global instance
window.MPesewa = new MPesewaApp();

// Auto-start on page load
document.addEventListener('DOMContentLoaded', () => {
    MPesewa.start();
});

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = MPesewa;
}