/**
 * 🇸🇴 SOMALIA COUNTRY CONFIGURATION MODULE
 * 
 * STRICT HIERARCHY ENFORCEMENT:
 * Global → Somalia Country → Groups → Lenders → Borrowers (Ledgers)
 * 
 * NON-NEGOTIABLE RULES:
 * 1. No cross-country lending/borrowing
 * 2. Groups are Somalia-only
 * 3. Currency: Somali Shilling (SOS)
 * 4. Country isolation enforced at all levels
 */

const SomaliaConfig = {
    // ============================================
    // 1️⃣ COUNTRY IDENTIFICATION
    // ============================================
    country: {
        code: 'SO',
        name: 'Somalia',
        fullName: 'Federal Republic of Somalia',
        isoCode: 'SO',
        region: 'East Africa',
        timezone: 'Africa/Mogadishu',
        callingCode: '+252',
        flagEmoji: '🇸🇴',
        domain: 'mpesewa.so',
        language: 'Somali (official), Arabic',
        population: '17+ million',
        capital: 'Mogadishu'
    },

    // ============================================
    // 2️⃣ CURRENCY & FINANCIAL CONFIGURATION
    // ============================================
    currency: {
        code: 'SOS',
        symbol: 'S',
        name: 'Somali Shilling',
        decimalPlaces: 2,
        format: 'S {amount}',
        exchangeRateUSD: 570, // Approximate rate
        dailyFluctuationLimit: 2.5, // Max daily fluctuation percentage
        
        // Currency validation rules
        validation: {
            minAmount: 100, // Minimum 100 SOS (≈ $0.18)
            maxAmount: 1000000, // Maximum 1,000,000 SOS (≈ $1,754)
            transactionLimits: {
                daily: 500000,
                weekly: 2000000,
                monthly: 5000000
            }
        }
    },

    // ============================================
    // 3️⃣ REGULATORY COMPLIANCE
    // ============================================
    regulations: {
        financialAuthority: 'Central Bank of Somalia',
        licenseNumber: 'CBS/FI/2023/MP-0456',
        complianceFramework: 'Somalia Financial Services Act 2022',
        taxRequirements: {
            vatRate: 0, // No VAT for micro-lending
            withholdingTax: 5,
            reportingThreshold: 1000000
        },
        
        // KYC Requirements
        kycRequirements: {
            mandatory: true,
            levels: [
                {
                    level: 1,
                    maxAmount: 50000,
                    requirements: ['Phone Number', 'Full Name']
                },
                {
                    level: 2,
                    maxAmount: 200000,
                    requirements: ['National ID', 'Photo', 'Address']
                },
                {
                    level: 3,
                    maxAmount: 1000000,
                    requirements: ['Biometric Verification', 'Income Proof']
                }
            ]
        }
    },

    // ============================================
    // 4️⃣ PLATFORM HIERARCHY CONFIGURATION
    // ============================================
    hierarchy: {
        // STRICT HIERARCHY ENFORCEMENT
        structure: {
            global: {
                name: 'Global',
                children: ['countries']
            },
            country: {
                name: 'Somalia',
                children: ['groups'],
                isolation: {
                    enabled: true,
                    crossCountryAccess: false,
                    crossCountryTransactions: false,
                    dataLocalization: true
                }
            },
            groups: {
                name: 'Groups',
                children: ['lenders', 'borrowers'],
                limits: {
                    minMembers: 5,
                    maxMembers: 1000,
                    maxGroupsPerUser: 4,
                    minLendersPerGroup: 1,
                    maxBorrowersPerGroup: 999
                }
            },
            lenders: {
                name: 'Lenders',
                children: ['ledgers'],
                requirements: {
                    subscription: true,
                    verification: true,
                    minAge: 18
                }
            },
            borrowers: {
                name: 'Borrowers',
                children: [],
                requirements: {
                    subscription: false,
                    verification: true,
                    minAge: 18,
                    maxActiveLoans: 1
                }
            },
            ledgers: {
                name: 'Ledgers',
                children: [],
                properties: {
                    autoGenerated: true,
                    unlimitedPerLender: true,
                    linkedToBorrower: true
                }
            }
        },

        // ENFORCEMENT RULES
        enforcement: {
            countryLock: {
                enabled: true,
                registrationLock: true,
                ipGeolocationCheck: true,
                phoneNumberValidation: true
            },
            groupIsolation: {
                lendingWithinGroupOnly: true,
                borrowerVisibilityLimited: true,
                adminModerationRequired: true
            },
            roleSeparation: {
                dualRolesAllowed: true,
                separateProfilesRequired: true,
                dashboardSeparation: true
            }
        }
    },

    // ============================================
    // 5️⃣ USER ROLES & PERMISSIONS
    // ============================================
    roles: {
        // Borrower Role Configuration
        borrower: {
            name: 'Borrower',
            permissions: {
                canBorrow: true,
                canRepay: true,
                canJoinGroups: true,
                canViewOwnLedger: true,
                canRequestLoan: true,
                canSeeLenders: false,
                canSeeOtherBorrowers: false,
                maxGroups: 4,
                subscriptionRequired: false
            },
            requirements: {
                verification: ['phone', 'id'],
                referralCount: 2,
                minimumRating: 3.0
            }
        },

        // Lender Role Configuration
        lender: {
            name: 'Lender',
            permissions: {
                canLend: true,
                canCreateLedgers: true,
                canRateBorrowers: true,
                canBlacklist: true,
                canViewPortfolio: true,
                canSeeBorrowers: true,
                subscriptionRequired: true,
                maxLedgers: 'unlimited'
            },
            requirements: {
                subscription: true,
                verification: ['phone', 'id', 'address'],
                minimumDeposit: 5000,
                creditCheck: false
            }
        },

        // Group Admin Role
        groupAdmin: {
            name: 'Group Admin',
            permissions: {
                canInviteMembers: true,
                canRemoveMembers: true,
                canModerateLoans: true,
                canResolveDisputes: true,
                canViewAllLedgers: true,
                canSetGroupRules: true
            },
            requirements: {
                mustBeFounder: true,
                minimumMembers: 5
            }
        },

        // Platform Admin Role (Somalia-specific)
        platformAdmin: {
            name: 'Somalia Platform Admin',
            permissions: {
                canOverrideBlacklist: true,
                canEditAnyLedger: true,
                canModerateRatings: true,
                canValidateCollectors: true,
                canFreezeAccounts: true,
                canViewAllData: true
            },
            scope: 'country' // Limited to Somalia only
        }
    },

    // ============================================
    // 6️⃣ SUBSCRIPTION TIERS (LENDERS ONLY)
    // ============================================
    subscriptions: {
        // STRICT: Borrowers pay NO subscription fees
        borrowerTiers: {
            basic: {
                name: 'Basic Borrower',
                cost: 0,
                features: [
                    'Access to 20 emergency categories',
                    'Maximum 4 groups',
                    'Loan requests up to 50,000 SOS',
                    '7-day repayment terms',
                    'Community rating system'
                ]
            }
        },

        // LENDER SUBSCRIPTION TIERS (MANDATORY)
        lenderTiers: {
            basic: {
                name: 'Basic Lender',
                weeklyLimit: 1500,
                monthlyCost: 50,
                biAnnualCost: 250,
                annualCost: 500,
                features: [
                    'Lend up to 1,500 SOS per week',
                    'Unlimited ledgers',
                    'Basic borrower ratings',
                    'Group lending only',
                    'No CRB check required'
                ],
                restrictions: [
                    'Cannot lend above 1,500 SOS weekly',
                    'No cross-group lending',
                    'Subscription expires 28th monthly'
                ]
            },

            premium: {
                name: 'Premium Lender',
                weeklyLimit: 5000,
                monthlyCost: 250,
                biAnnualCost: 1500,
                annualCost: 2500,
                features: [
                    'Lend up to 5,000 SOS per week',
                    'Advanced portfolio analytics',
                    'Priority borrower matching',
                    'Extended ledger history',
                    'No CRB check required'
                ],
                restrictions: [
                    'Maximum 10,000 SOS in active ledgers',
                    'Country-locked operations'
                ]
            },

            super: {
                name: 'Super Lender',
                weeklyLimit: 20000,
                monthlyCost: 1000,
                biAnnualCost: 5000,
                annualCost: 8500,
                features: [
                    'Lend up to 20,000 SOS per week',
                    'CRB check access',
                    'Advanced risk analytics',
                    'Priority support',
                    'Bulk lending tools'
                ],
                restrictions: [
                    'CRB check mandatory',
                    'Maximum 20,000 SOS per ledger',
                    'Enhanced KYC required'
                ]
            },

            lenderOfLenders: {
                name: 'Lender of Lenders',
                weeklyLimit: 50000,
                monthlyCost: 500,
                biAnnualCost: 3500,
                annualCost: 6500,
                features: [
                    'Lend up to 50,000 SOS',
                    'Custom interest rates',
                    'Extended repayment periods (min 1 month)',
                    'Wholesale lending tools',
                    'Dedicated account manager'
                ],
                restrictions: [
                    'CRB check mandatory',
                    'Minimum 1-month repayment period',
                    'Enhanced due diligence'
                ]
            }
        },

        // ENFORCEMENT RULES
        enforcement: {
            expiryDate: 28, // 28th of every month
            gracePeriod: 0, // No grace period
            blockingRules: {
                expiredSubscription: 'Full platform access blocked',
                overduePayment: 'Lending suspended immediately',
                tierDowngrade: 'Existing loans unaffected'
            },
            paymentMethods: {
                mpesa: false, // Not available in Somalia
                evcPlus: true,
                sahal: true,
                bankTransfer: true,
                cash: true
            }
        }
    },

    // ============================================
    // 7️⃣ LOAN RULES & PARAMETERS
    // ============================================
    loans: {
        // General Loan Rules
        general: {
            repaymentPeriod: 7, // Days
            interestRate: 10, // Percentage
            minLoanAmount: 100, // 100 SOS
            maxLoanAmount: 50000, // Based on tier
            partialRepayments: true,
            maxActiveLoans: 1
        },

        // Penalty Structure
        penalties: {
            after7Days: {
                dailyPenalty: 5, // Percentage daily
                maxPenaltyDays: 53, // Until 60 days total
                calculation: 'On outstanding balance'
            },
            default: {
                afterDays: 60, // 2 months
                action: 'Blacklist automatically',
                consequences: [
                    'Cannot borrow',
                    'Cannot join new groups',
                    'Public blacklist badge',
                    'Debt collection initiated'
                ]
            }
        },

        // Emergency Categories (Somalia-specific)
        categories: [
            {
                id: 'fare',
                name: 'M-pesewa Fare',
                icon: '🚌',
                description: 'Transport money for daily commute',
                maxAmount: 5000,
                typicalUse: 'Bus, taxi, boda-boda fares'
            },
            {
                id: 'data',
                name: 'M-pesewa Data',
                icon: '📶',
                description: 'Mobile internet bundles',
                maxAmount: 2000,
                typicalUse: 'Social media, communication, work'
            },
            {
                id: 'gas',
                name: 'M-pesewa Cooking Gas',
                icon: '🔥',
                description: 'Cooking gas refills',
                maxAmount: 8000,
                typicalUse: 'Household cooking needs'
            },
            {
                id: 'food',
                name: 'M-pesewa Food',
                icon: '🍲',
                description: 'Emergency food supplies',
                maxAmount: 10000,
                typicalUse: 'Basic groceries, meals'
            },
            {
                id: 'water',
                name: 'M-pesewa Water',
                icon: '🚰',
                description: 'Water bills and supplies',
                maxAmount: 5000,
                typicalUse: 'Drinking water, bills'
            },
            {
                id: 'medicine',
                name: 'M-pesewa Medicine',
                icon: '💊',
                description: 'Emergency medical supplies',
                maxAmount: 15000,
                typicalUse: 'Prescription drugs, first aid'
            },
            {
                id: 'school',
                name: 'M-pesewa School Fees',
                icon: '🎓',
                description: 'Education-related expenses',
                maxAmount: 20000,
                typicalUse: 'Tuition, books, uniforms'
            }
        ]
    },

    // ============================================
    // 8️⃣ REPUTATION & BLACKLIST SYSTEM
    // ============================================
    reputation: {
        // Rating System
        rating: {
            scale: 5,
            criteria: [
                'Repayment punctuality',
                'Communication',
                'Loan purpose honesty',
                'Group participation'
            ],
            calculation: 'Average of last 10 ratings',
            impact: {
                goodRating: 'Access to more groups',
                poorRating: 'Limited borrowing capacity',
                minimumRating: 2.0 // Below this cannot borrow
            }
        },

        // Blacklist System
        blacklist: {
            trigger: '60 days overdue',
            automatic: true,
            visibility: 'Platform-wide badge',
            restrictions: [
                'Cannot borrow new loans',
                'Cannot join new groups',
                'Public listing in defaulters registry'
            ],
            removal: {
                by: 'Platform Admin only',
                conditions: [
                    'Full repayment (principal + interest + penalties)',
                    'Admin approval required',
                    'Waiting period: 30 days'
                ]
            }
        }
    },

    // ============================================
    // 9️⃣ DATA & PRIVACY RULES
    // ============================================
    dataPrivacy: {
        storage: {
            location: 'Somalia',
            retentionPeriod: '7 years',
            backupFrequency: 'Daily'
        },
        sharing: {
            withinGroup: 'Limited profile visible',
            crossGroup: 'No data sharing',
            thirdParties: 'Debt collectors only with consent',
            government: 'As required by Somali law'
        },
        userRights: [
            'Right to access personal data',
            'Right to correction',
            'Right to data portability',
            'Right to be forgotten (with conditions)'
        ]
    },

    // ============================================
    // 🔟 OPERATIONAL PARAMETERS
    // ============================================
    operations: {
        supportHours: {
            weekdays: '8:00 AM - 6:00 PM',
            weekends: '9:00 AM - 2:00 PM',
            holidays: 'Emergency support only'
        },
        contact: {
            phone: '+252 63 0000000',
            email: 'somalia@mpesewa.com',
            address: 'Mogadishu, Somalia',
            emergency: '+252 61 0000000'
        },
        maintenance: {
            window: 'Sunday 2:00 AM - 4:00 AM',
            noticePeriod: '48 hours'
        }
    },

    // ============================================
    // 1️⃣1️⃣ VALIDATION & SANITY CHECKS
    // ============================================
    validation: {
        phoneNumber: {
            format: '+252XXXXXXXXX',
            length: 12,
            regex: /^\+252[0-9]{9}$/,
            carrierDetection: true
        },
        nationalId: {
            format: 'SO-XXXX-XXXX-XXXX',
            length: 19,
            regex: /^SO-[0-9]{4}-[0-9]{4}-[0-9]{4}$/
        },
        location: {
            requiredRegions: ['Banaadir', 'Somaliland', 'Puntland'],
            verification: 'Postal code or district'
        }
    },

    // ============================================
    // 1️⃣2️⃣ FALLBACK & ERROR HANDLING
    // ============================================
    fallback: {
        currencyFallback: 'USD',
        languageFallback: 'English',
        supportFallback: 'global@mpesewa.com',
        systemDowntime: {
            maxAllowed: '2 hours',
            compensation: 'Subscription extension',
            notification: 'SMS and in-app'
        }
    },

    // ============================================
    // 1️⃣3️⃣ EXPORT CONFIGURATION
    // ============================================
    export: {
        enabled: true,
        formats: ['CSV', 'PDF', 'Excel'],
        frequency: 'Monthly',
        retention: '7 years'
    }
};

// ============================================
// CONFIGURATION VALIDATION
// ============================================
const validateSomaliaConfig = () => {
    const errors = [];
    
    // Hierarchy validation
    if (!SomaliaConfig.hierarchy.structure.country.isolation.enabled) {
        errors.push('Country isolation MUST be enabled for Somalia');
    }
    
    // Currency validation
    if (SomaliaConfig.currency.code !== 'SOS') {
        errors.push('Currency MUST be SOS for Somalia');
    }
    
    // Subscription validation
    if (SomaliaConfig.subscriptions.borrowerTiers.basic.cost !== 0) {
        errors.push('Borrowers MUST have zero subscription cost');
    }
    
    // Loan rules validation
    if (SomaliaConfig.loans.general.interestRate !== 10) {
        errors.push('Interest rate MUST be 10%');
    }
    
    if (errors.length > 0) {
        console.error('❌ Somalia Configuration Validation Failed:');
        errors.forEach(error => console.error(`  - ${error}`));
        throw new Error('Somalia configuration invalid');
    }
    
    console.log('✅ Somalia Configuration Validated Successfully');
    return true;
};

// ============================================
// HIERARCHY ENFORCEMENT FUNCTIONS
// ============================================
const SomaliaHierarchy = {
    /**
     * Validate user belongs to Somalia
     * @param {Object} user - User object
     * @returns {boolean} - True if user is in Somalia
     */
    validateCountry: (user) => {
        if (!user || !user.country) return false;
        return user.country.toUpperCase() === 'SO';
    },
    
    /**
     * Enforce group isolation
     * @param {string} lenderGroupId - Lender's group ID
     * @param {string} borrowerGroupId - Borrower's group ID
     * @returns {boolean} - True if lending allowed
     */
    validateGroupIsolation: (lenderGroupId, borrowerGroupId) => {
        return lenderGroupId === borrowerGroupId;
    },
    
    /**
     * Check if user can join more groups
     * @param {Object} user - User object
     * @param {number} currentGroups - Current groups count
     * @returns {boolean} - True if can join more
     */
    canJoinMoreGroups: (user, currentGroups) => {
        if (user.role === 'borrower') {
            return currentGroups < SomaliaConfig.hierarchy.structure.groups.limits.maxGroupsPerUser;
        }
        return true; // Lenders have no group limit
    },
    
    /**
     * Validate subscription status for lender
     * @param {Object} lender - Lender object
     * @returns {Object} - Validation result
     */
    validateLenderSubscription: (lender) => {
        const today = new Date();
        const expiryDate = new Date(lender.subscription.expiry);
        
        return {
            isValid: today <= expiryDate,
            daysRemaining: Math.ceil((expiryDate - today) / (1000 * 60 * 60 * 24)),
            expiryDay: expiryDate.getDate(),
            isExpiryMonth: today.getDate() === 28 && today.getMonth() === expiryDate.getMonth()
        };
    }
};

// ============================================
// COUNTRY-SPECIFIC UTILITIES
// ============================================
const SomaliaUtils = {
    /**
     * Format currency for Somalia
     * @param {number} amount - Amount in SOS
     * @returns {string} - Formatted currency
     */
    formatCurrency: (amount) => {
        return `S ${amount.toLocaleString('en-SO')}`;
    },
    
    /**
     * Calculate loan repayment
     * @param {number} principal - Loan amount
     * @param {number} days - Days overdue (0-7 normal, >7 penalty)
     * @returns {Object} - Repayment details
     */
    calculateRepayment: (principal, days = 7) => {
        const interest = principal * 0.10; // 10% interest
        let penalty = 0;
        
        if (days > 7) {
            const overdueDays = days - 7;
            penalty = principal * 0.05 * overdueDays; // 5% daily penalty
        }
        
        const total = principal + interest + penalty;
        
        return {
            principal,
            interest,
            penalty,
            total,
            breakdown: {
                dailyRepayment: total / 7,
                weeklyTotal: total,
                penaltyStarts: days > 7 ? 'Day 8' : 'No penalty'
            }
        };
    },
    
    /**
     * Validate Somali phone number
     * @param {string} phone - Phone number
     * @returns {boolean} - True if valid
     */
    validatePhone: (phone) => {
        const regex = SomaliaConfig.validation.phoneNumber.regex;
        return regex.test(phone);
    },
    
    /**
     * Get tier limits for lender
     * @param {string} tier - Subscription tier
     * @returns {Object} - Tier limits
     */
    getTierLimits: (tier) => {
        const tiers = SomaliaConfig.subscriptions.lenderTiers;
        return tiers[tier] || tiers.basic;
    }
};

// ============================================
// EXPORT MODULE
// ============================================
module.exports = {
    config: SomaliaConfig,
    hierarchy: SomaliaHierarchy,
    utils: SomaliaUtils,
    validateConfig: validateSomaliaConfig,
    
    // Constants
    CONSTANTS: {
        COUNTRY_CODE: 'SO',
        CURRENCY: 'SOS',
        TIMEZONE: 'Africa/Mogadishu',
        MAX_GROUPS_PER_BORROWER: 4,
        MIN_GROUP_MEMBERS: 5,
        MAX_GROUP_MEMBERS: 1000,
        SUBSCRIPTION_EXPIRY_DAY: 28,
        LOAN_INTEREST_RATE: 10,
        PENALTY_RATE: 5,
        DEFAULT_PERIOD_DAYS: 60
    }
};

// ============================================
// INITIALIZATION
// ============================================
(() => {
    try {
        validateSomaliaConfig();
        console.log(`🇸🇴 Somalia Module Loaded Successfully`);
        console.log(`   Currency: ${SomaliaConfig.currency.code}`);
        console.log(`   Hierarchy: ${SomaliaConfig.hierarchy.structure.country.name}`);
        console.log(`   Subscription Expiry: ${SomaliaConfig.subscriptions.enforcement.expiryDate}th monthly`);
        console.log(`   Loan Interest: ${SomaliaConfig.loans.general.interestRate}%`);
    } catch (error) {
        console.error(`❌ Somalia Module Failed to Load: ${error.message}`);
        process.exit(1);
    }
})();