/**
 * M-PESEWA UGANDA RULES MODULE
 * STRICT ENFORCEMENT OF UGANDA-SPECIFIC RULES
 * Last Updated: 2024-01-24
 * Version: 1.0.0
 */

import { getUgandaCurrency } from './ug.currency.js';

class UgandaRules {
    constructor() {
        this.currency = getUgandaCurrency();
        this.countryCode = 'UG';
        this.countryName = 'Uganda';
        
        // ============================================
        // STRICT HIERARCHY ENFORCEMENT
        // ============================================
        this.hierarchy = {
            global: 'M-Pesewa',
            country: 'UG',
            groups: {
                minMembers: 5,
                maxMembers: 1000,
                types: ['Family', 'Church', 'Professional', 'Local', 'Social', 'Business'],
                invitationOnly: true,
                countryLocked: true,
                maxGroupsPerUser: 4,
                minRatingForMultiGroup: 3 // 3-star rating minimum
            },
            lenders: {
                minPerGroup: 1,
                maxPerGroup: null, // No limit, but group max is 1000
                subscriptionRequired: true,
                canAlsoBeBorrowers: true,
                dualRoleRequirement: 'separate_profiles'
            },
            ledgers: {
                autoGenerated: true,
                unlimitedPerLender: true,
                fields: [
                    'borrower_name',
                    'borrower_contact',
                    'borrower_location',
                    'guarantor1_contact',
                    'guarantor2_contact',
                    'loan_category',
                    'amount_borrowed',
                    'date_borrowed',
                    'due_date',
                    'interest_rate',
                    'penalty_rate',
                    'status',
                    'amount_overdue'
                ],
                statuses: ['active', 'cleared', 'defaulted', 'disputed']
            },
            borrowers: {
                noSubscription: true,
                maxActiveLoans: 1,
                ratingSystem: '5-star',
                blacklistThreshold: 60, // days
                repaymentGracePeriod: 0 // No grace period
            }
        };

        // ============================================
        // UGANDA-SPECIFIC LEGAL RULES
        // ============================================
        this.legalRules = {
            regulatoryBody: 'Bank of Uganda',
            licenseNumber: 'MPES/UG/2024/001',
            maxInterestRate: 0.10, // 10% weekly maximum
            coolingOffPeriod: 0, // No cooling off period
            disputeResolution: 'Uganda Financial Intelligence Authority',
            dataProtection: 'Data Protection and Privacy Act, 2019',
            
            // Required disclosures
            disclosures: [
                'All loans are private agreements between users',
                'M-Pesewa is not a bank and does not hold funds',
                'Default may affect credit rating',
                'Blacklisted users cannot borrow or join new groups',
                'Platform admin can override ledger entries'
            ],
            
            // Prohibited activities
            prohibited: [
                'Cross-country lending',
                'Lending outside registered groups',
                'Charging hidden fees',
                'Harassment of borrowers',
                'Usury (interest above 10% weekly)',
                'Money laundering activities'
            ]
        };

        // ============================================
        // GROUP MANAGEMENT RULES
        // ============================================
        this.groupRules = {
            creation: {
                minAge: 18,
                nationalIdRequired: true,
                phoneVerificationRequired: true,
                locationVerificationRequired: true,
                initialMembersRequired: 5,
                groupNameUniqueness: 'within_country'
            },
            
            membership: {
                maxGroupsPerUser: 4,
                minRatingForNewGroup: 3,
                referralRequired: true,
                twoGuarantorsRequired: true,
                backgroundCheck: 'phone_verification',
                exitRules: {
                    activeLoans: 'must_clear_all_loans',
                    ongoingObligations: 'must_fulfill',
                    ratingImpact: 'exit_rating_recorded'
                }
            },
            
            administration: {
                singleAdmin: true,
                adminPowers: [
                    'invite_members',
                    'remove_members',
                    'moderate_disputes',
                    'view_group_analytics',
                    'set_internal_rules'
                ],
                adminTransfer: 'possible_with_consent',
                adminRemoval: 'platform_admin_only'
            }
        };

        // ============================================
        // LENDER-SPECIFIC RULES
        // ============================================
        this.lenderRules = {
            eligibility: {
                minAge: 21,
                nationalIdRequired: true,
                bankAccountRequired: false,
                creditCheck: 'for_super_tier_only',
                residenceVerification: true,
                criminalRecordCheck: 'for_large_amounts'
            },
            
            subscription: {
                mandatory: true,
                expiryDate: '28th_of_each_month',
                gracePeriod: 0,
                autoRenewal: false,
                proratedRefunds: false,
                tierUpgrade: 'immediate_upon_payment',
                tierDowngrade: 'end_of_period_only'
            },
            
            lendingLimits: {
                perLoan: 'tier_based',
                perBorrower: 'unlimited_within_limit',
                perGroup: 'unlimited_within_limit',
                daily: 'no_limit',
                weekly: 'tier_based',
                monthly: 'tier_based'
            },
            
            responsibilities: {
                ledgerMaintenance: 'manual_updates_required',
                repaymentTracking: 'lender_responsibility',
                disputeResolution: 'first_level_resolution',
                blacklistAuthority: 'can_blacklist_defaulters',
                ratingAuthority: 'can_rate_borrowers'
            }
        };

        // ============================================
        // BORROWER-SPECIFIC RULES
        // ============================================
        this.borrowerRules = {
            eligibility: {
                minAge: 18,
                nationalIdRequired: true,
                phoneNumberRequired: true,
                locationRequired: true,
                existingGroups: 'max_4_with_good_rating',
                blacklistStatus: 'cannot_borrow_if_blacklisted'
            },
            
            borrowingLimits: {
                perLoan: 'tier_based',
                activeLoans: '1_per_group',
                totalExposure: 'across_all_groups',
                timeBetweenLoans: 'no_restriction',
                groupSpecificLimits: 'group_admin_can_set'
            },
            
            repayment: {
                period: 7,
                interest: 0.10,
                partialPayments: 'allowed',
                gracePeriod: 0,
                penalty: '5%_daily_after_7_days',
                defaultPeriod: 60
            },
            
            consequences: {
                latePayment: 'penalty_applied',
                default: 'blacklist_after_60_days',
                blacklistRemoval: 'admin_approval_required',
                ratingImpact: 'affects_future_access'
            }
        };

        // ============================================
        // LEDGER MANAGEMENT RULES
        // ============================================
        this.ledgerRules = {
            creation: {
                automatic: true,
                fields: this.hierarchy.ledgers.fields,
                validation: 'pre_save_validation',
                duplicates: 'not_allowed'
            },
            
            maintenance: {
                updates: 'manual_by_lender',
                corrections: 'admin_override_possible',
                auditTrail: 'mandatory',
                versioning: 'maintain_history'
            },
            
            closure: {
                conditions: ['full_repayment', 'settlement_agreement', 'write_off'],
                documentation: 'required',
                archiving: 'permanent',
                reactivation: 'not_allowed'
            }
        };

        // ============================================
        // REPUTATION SYSTEM RULES
        // ============================================
        this.reputationRules = {
            ratingSystem: {
                scale: '1_to_5_stars',
                criteria: ['timeliness', 'communication', 'honesty', 'cooperation'],
                weighted: true,
                decay: '6_months',
                minimumForBenefits: 3
            },
            
            blacklist: {
                trigger: '60_days_default',
                visibility: 'platform_wide',
                restrictions: ['no_borrowing', 'no_new_groups', 'reputation_impact'],
                removal: ['full_repayment', 'admin_approval'],
                appeals: 'admin_discretion'
            },
            
            benefits: {
                goodRating: ['more_groups', 'higher_limits', 'lower_interest'],
                excellentRating: ['priority_support', 'fee_waivers', 'early_access']
            }
        };

        // ============================================
        // DISPUTE RESOLUTION RULES
        // ============================================
        this.disputeRules = {
            escalation: {
                level1: 'direct_negotiation',
                level2: 'group_admin',
                level3: 'platform_admin',
                level4: 'legal_authorities'
            },
            
            timeframes: {
                initialResponse: '24_hours',
                groupResolution: '7_days',
                platformResolution: '14_days',
                finalAppeal: '30_days'
            },
            
            evidence: {
                required: ['loan_agreement', 'communication_records', 'payment_proof'],
                formats: ['text', 'images', 'documents', 'audio'],
                storage: 'encrypted_30_days'
            }
        };

        // ============================================
        // SECURITY AND COMPLIANCE RULES
        // ============================================
        this.securityRules = {
            authentication: {
                password: '8_12_chars_mixed',
                twoFactor: 'optional',
                biometric: 'supported',
                sessionTimeout: '30_minutes',
                concurrentSessions: 2
            },
            
            dataProtection: {
                encryption: 'end_to_end',
                storage: 'uganda_servers',
                retention: '7_years',
                deletion: 'upon_request',
                breachProtocol: '24_hour_notification'
            },
            
            monitoring: {
                suspiciousActivity: 'real_time',
                fraudDetection: 'automated',
                auditLogs: 'comprehensive',
                reporting: 'regulatory_compliant'
            }
        };
    }

    // ============================================
    // HIERARCHY ENFORCEMENT METHODS
    // ============================================

    validateHierarchy(entity) {
        const errors = [];
        
        // Ensure country isolation
        if (entity.country !== this.countryCode) {
            errors.push(`Entity country ${entity.country} does not match Uganda (UG)`);
        }
        
        // Group validation
        if (entity.type === 'group') {
            if (!entity.members || entity.members.length < this.hierarchy.groups.minMembers) {
                errors.push(`Group must have at least ${this.hierarchy.groups.minMembers} members`);
            }
            
            if (entity.members && entity.members.length > this.hierarchy.groups.maxMembers) {
                errors.push(`Group cannot exceed ${this.hierarchy.groups.maxMembers} members`);
            }
        }
        
        // Lender validation
        if (entity.type === 'lender') {
            if (!entity.subscription) {
                errors.push('Lender must have active subscription');
            }
            
            if (entity.subscription && entity.subscription.country !== this.countryCode) {
                errors.push('Lender subscription must be for Uganda');
            }
        }
        
        // Borrower validation
        if (entity.type === 'borrower') {
            if (entity.blacklisted) {
                errors.push('Blacklisted borrowers cannot participate');
            }
            
            if (entity.groups && entity.groups.length > this.hierarchy.groups.maxGroupsPerUser) {
                errors.push(`Borrower cannot join more than ${this.hierarchy.groups.maxGroupsPerUser} groups`);
            }
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            hierarchy: this.hierarchy
        };
    }

    enforceCountryIsolation(source, target) {
        // Strict country isolation enforcement
        if (source.country !== target.country) {
            throw new UgandaRulesError(
                `Cross-country operation not allowed: ${source.country} to ${target.country}`,
                'COUNTRY_ISOLATION_VIOLATION'
            );
        }
        
        return {
            allowed: true,
            sourceCountry: source.country,
            targetCountry: target.country,
            message: 'Country isolation enforced'
        };
    }

    // ============================================
    // GROUP MANAGEMENT METHODS
    // ============================================

    validateGroupCreation(creator, groupData) {
        const errors = [];
        
        // Creator validation
        if (creator.age < this.groupRules.creation.minAge) {
            errors.push(`Creator must be at least ${this.groupRules.creation.minAge} years old`);
        }
        
        if (!creator.nationalId) {
            errors.push('National ID is required');
        }
        
        if (!creator.phoneVerified) {
            errors.push('Phone verification required');
        }
        
        // Group data validation
        if (!groupData.name || groupData.name.length < 3) {
            errors.push('Group name must be at least 3 characters');
        }
        
        if (!this.hierarchy.groups.types.includes(groupData.type)) {
            errors.push(`Group type must be one of: ${this.hierarchy.groups.types.join(', ')}`);
        }
        
        if (groupData.members && groupData.members.length < this.groupRules.creation.initialMembersRequired) {
            errors.push(`Initial ${this.groupRules.creation.initialMembersRequired} members required`);
        }
        
        return {
            canCreate: errors.length === 0,
            errors,
            requirements: this.groupRules.creation
        };
    }

    validateGroupMembership(user, group) {
        const errors = [];
        
        // User validation
        if (user.groups && user.groups.length >= this.hierarchy.groups.maxGroupsPerUser) {
            errors.push(`User already in ${user.groups.length} groups (max ${this.hierarchy.groups.maxGroupsPerUser})`);
        }
        
        if (user.rating < this.hierarchy.groups.minRatingForMultiGroup && user.groups.length > 0) {
            errors.push(`Minimum ${this.hierarchy.groups.minRatingForMultiGroup}-star rating required for multiple groups`);
        }
        
        if (!user.referral) {
            errors.push('Referral required for group membership');
        }
        
        if (!user.guarantors || user.guarantors.length < 2) {
            errors.push('Two guarantors required');
        }
        
        // Group validation
        if (group.members && group.members.length >= this.hierarchy.groups.maxMembers) {
            errors.push(`Group has reached maximum members (${this.hierarchy.groups.maxMembers})`);
        }
        
        if (group.country !== user.country) {
            errors.push('User and group must be in same country');
        }
        
        return {
            canJoin: errors.length === 0,
            errors,
            userStatus: {
                groups: user.groups ? user.groups.length : 0,
                rating: user.rating,
                country: user.country
            },
            groupStatus: {
                members: group.members ? group.members.length : 0,
                country: group.country,
                capacity: this.hierarchy.groups.maxMembers
            }
        };
    }

    // ============================================
    // LENDER VALIDATION METHODS
    // ============================================

    validateLenderRegistration(lenderData) {
        const errors = [];
        const warnings = [];
        
        // Age validation
        if (lenderData.age < this.lenderRules.eligibility.minAge) {
            errors.push(`Lenders must be at least ${this.lenderRules.eligibility.minAge} years old`);
        }
        
        // Identification
        if (!lenderData.nationalId) {
            errors.push('National ID is required');
        }
        
        if (!lenderData.phoneVerified) {
            errors.push('Phone verification required');
        }
        
        if (!lenderData.locationVerified) {
            errors.push('Location verification required');
        }
        
        // Subscription tier selection
        if (!lenderData.subscriptionTier) {
            errors.push('Subscription tier must be selected');
        } else {
            const tier = this.currency.config.subscriptionTiers[lenderData.subscriptionTier];
            if (!tier) {
                errors.push(`Invalid subscription tier: ${lenderData.subscriptionTier}`);
            }
        }
        
        // Categories selection
        if (!lenderData.categories || lenderData.categories.length === 0) {
            warnings.push('No lending categories selected - will not receive loan requests');
        }
        
        // For Super tier and above
        if (['super', 'lenderOfLenders'].includes(lenderData.subscriptionTier)) {
            if (!lenderData.creditCheck) {
                errors.push('Credit check required for Super tier and above');
            }
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            warnings,
            eligibility: this.lenderRules.eligibility
        };
    }

    validateLenderSubscription(lender, subscriptionData) {
        const errors = [];
        
        // Check if subscription expired
        const today = new Date();
        const expiry = new Date(subscriptionData.expiryDate);
        
        if (today > expiry) {
            errors.push('Subscription expired');
        }
        
        // Check if subscription is for correct country
        if (subscriptionData.country !== this.countryCode) {
            errors.push(`Subscription is for ${subscriptionData.country}, not Uganda`);
        }
        
        // Check if tier matches lender's tier
        if (subscriptionData.tier !== lender.subscriptionTier) {
            errors.push(`Subscription tier mismatch: ${subscriptionData.tier} vs ${lender.subscriptionTier}`);
        }
        
        return {
            canLend: errors.length === 0,
            errors,
            subscriptionStatus: {
                tier: subscriptionData.tier,
                expiry: subscriptionData.expiryDate,
                country: subscriptionData.country,
                daysRemaining: Math.ceil((expiry - today) / (1000 * 60 * 60 * 24))
            }
        };
    }

    // ============================================
    // BORROWER VALIDATION METHODS
    // ============================================

    validateBorrowerRegistration(borrowerData) {
        const errors = [];
        
        // Basic eligibility
        if (borrowerData.age < this.borrowerRules.eligibility.minAge) {
            errors.push(`Borrowers must be at least ${this.borrowerRules.eligibility.minAge} years old`);
        }
        
        if (!borrowerData.nationalId) {
            errors.push('National ID is required');
        }
        
        if (!borrowerData.phoneNumber) {
            errors.push('Phone number is required');
        }
        
        if (!borrowerData.location) {
            errors.push('Location is required');
        }
        
        // Blacklist check
        if (borrowerData.blacklisted) {
            errors.push('Blacklisted users cannot register as borrowers');
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            eligibility: this.borrowerRules.eligibility
        };
    }

    validateLoanRequest(borrower, loanData, group) {
        const errors = [];
        const warnings = [];
        
        // Borrower validation
        if (borrower.blacklisted) {
            errors.push('Blacklisted borrowers cannot request loans');
        }
        
        if (borrower.activeLoans && borrower.activeLoans >= this.borrowerRules.borrowingLimits.activeLoans) {
            errors.push(`Maximum ${this.borrowerRules.borrowingLimits.activeLoans} active loan(s) allowed`);
        }
        
        if (borrower.rating < 2) {
            errors.push('Minimum 2-star rating required for borrowing');
        }
        
        // Loan amount validation
        const currencyValidation = this.currency.validateLoanRequest(
            loanData.amount,
            borrower.rating,
            borrower.activeLoans || 0
        );
        
        if (!currencyValidation.isValid) {
            errors.push(...currencyValidation.errors);
        }
        
        // Group validation
        if (!group) {
            errors.push('Group selection required');
        } else if (group.country !== this.countryCode) {
            errors.push('Group must be in Uganda');
        }
        
        // Lender selection
        if (!loanData.lenderId) {
            warnings.push('No specific lender selected - request will be visible to all group lenders');
        }
        
        // Category validation
        if (!loanData.category) {
            errors.push('Loan category must be specified');
        }
        
        return {
            canBorrow: errors.length === 0,
            errors,
            warnings,
            suggested: currencyValidation.suggestedAmount,
            limits: this.borrowerRules.borrowingLimits
        };
    }

    // ============================================
    // LEDGER MANAGEMENT METHODS
    // ============================================

    validateLedgerCreation(loanApproval) {
        const errors = [];
        
        // Required fields check
        const requiredFields = this.hierarchy.ledgers.fields;
        for (const field of requiredFields) {
            if (!loanApproval[field] && field !== 'amount_overdue') {
                errors.push(`Missing required field: ${field}`);
            }
        }
        
        // Amount validation
        if (!this.currency.isValidAmount(loanApproval.amount_borrowed)) {
            errors.push('Invalid loan amount');
        }
        
        // Date validation
        const borrowedDate = new Date(loanApproval.date_borrowed);
        const dueDate = new Date(loanApproval.due_date);
        
        if (dueDate <= borrowedDate) {
            errors.push('Due date must be after borrowed date');
        }
        
        const daysDifference = (dueDate - borrowedDate) / (1000 * 60 * 60 * 24);
        if (daysDifference !== this.borrowerRules.repayment.period) {
            errors.push(`Repayment period must be ${this.borrowerRules.repayment.period} days`);
        }
        
        // Interest validation
        if (loanApproval.interest_rate !== this.borrowerRules.repayment.interest) {
            errors.push(`Interest rate must be ${this.borrowerRules.repayment.interest * 100}%`);
        }
        
        return {
            canCreateLedger: errors.length === 0,
            errors,
            ledgerData: {
                fields: requiredFields,
                status: 'active',
                created: new Date().toISOString()
            }
        };
    }

    calculateLedgerUpdates(ledger, payment) {
        const errors = [];
        const updates = {};
        
        // Validate payment
        if (!this.currency.isValidAmount(payment.amount)) {
            errors.push('Invalid payment amount');
        }
        
        if (payment.amount <= 0) {
            errors.push('Payment amount must be positive');
        }
        
        // Calculate outstanding
        const totalRepayment = this.currency.calculateTotalRepayment(ledger.amount_borrowed);
        const totalPaid = (ledger.amount_paid || 0) + payment.amount;
        const outstanding = totalRepayment - totalPaid;
        
        // Check if payment exceeds outstanding
        if (payment.amount > outstanding) {
            errors.push(`Payment exceeds outstanding amount. Maximum payment: ${this.currency.format(outstanding)}`);
        }
        
        // Calculate penalty if overdue
        const today = new Date();
        const dueDate = new Date(ledger.due_date);
        const overdueDays = Math.max(0, Math.ceil((today - dueDate) / (1000 * 60 * 60 * 24)));
        
        let penalty = 0;
        if (overdueDays > 7) {
            penalty = this.currency.calculateDailyPenalty(outstanding, overdueDays);
        }
        
        updates.amount_paid = totalPaid;
        updates.amount_outstanding = outstanding + penalty;
        updates.last_payment_date = today.toISOString();
        updates.overdue_days = overdueDays;
        updates.penalty_applied = penalty;
        
        // Update status
        if (updates.amount_outstanding <= 0) {
            updates.status = 'cleared';
            updates.cleared_date = today.toISOString();
        } else if (overdueDays >= this.borrowerRules.repayment.defaultPeriod) {
            updates.status = 'defaulted';
            updates.default_date = today.toISOString();
        } else if (overdueDays > 0) {
            updates.status = 'overdue';
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            updates,
            summary: {
                totalRepayment: this.currency.format(totalRepayment),
                paid: this.currency.format(totalPaid),
                outstanding: this.currency.format(outstanding),
                penalty: this.currency.format(penalty),
                totalOutstanding: this.currency.format(outstanding + penalty),
                overdueDays
            }
        };
    }

    // ============================================
    // REPUTATION SYSTEM METHODS
    // ============================================

    calculateBorrowerRating(repaymentHistory) {
        if (!repaymentHistory || repaymentHistory.length === 0) {
            return 3; // Default rating for new borrowers
        }
        
        let totalScore = 0;
        let weightSum = 0;
        
        repaymentHistory.forEach((repayment, index) => {
            // Recent repayments have higher weight
            const weight = Math.pow(0.9, index); // Exponential decay
            
            let score = 0;
            
            // Timeliness (40% weight)
            if (repayment.daysLate === 0) {
                score += 40;
            } else if (repayment.daysLate <= 3) {
                score += 30;
            } else if (repayment.daysLate <= 7) {
                score += 20;
            } else {
                score += 10;
            }
            
            // Amount paid (30% weight)
            if (repayment.amountPaid >= repayment.amountDue) {
                score += 30;
            } else if (repayment.amountPaid >= repayment.amountDue * 0.8) {
                score += 20;
            } else if (repayment.amountPaid >= repayment.amountDue * 0.5) {
                score += 15;
            } else {
                score += 5;
            }
            
            // Communication (20% weight)
            if (repayment.communication === 'excellent') {
                score += 20;
            } else if (repayment.communication === 'good') {
                score += 15;
            } else if (repayment.communication === 'fair') {
                score += 10;
            } else {
                score += 5;
            }
            
            // Previous rating (10% weight)
            score += (repayment.previousRating || 3) * 2.5;
            
            totalScore += (score * weight);
            weightSum += weight;
        });
        
        const averageScore = totalScore / weightSum;
        const rating = Math.min(5, Math.max(1, Math.round(averageScore / 20))); // Convert to 1-5 scale
        
        return rating;
    }

    determineBlacklistStatus(borrower, ledger) {
        const today = new Date();
        const dueDate = new Date(ledger.due_date);
        const overdueDays = Math.ceil((today - dueDate) / (1000 * 60 * 60 * 24));
        
        if (overdueDays < this.reputationRules.blacklist.trigger) {
            return {
                isBlacklisted: false,
                reason: 'Not yet reached blacklist threshold',
                daysRemaining: this.reputationRules.blacklist.trigger - overdueDays,
                actions: ['continue_normal_repayment', 'contact_lender']
            };
        }
        
        if (overdueDays >= this.reputationRules.blacklist.trigger) {
            return {
                isBlacklisted: true,
                reason: `Defaulted for ${overdueDays} days`,
                blacklistedDate: today.toISOString(),
                restrictions: this.reputationRules.blacklist.restrictions,
                removalConditions: this.reputationRules.blacklist.removal,
                actions: ['full_repayment_required', 'admin_approval_needed']
            };
        }
        
        return {
            isBlacklisted: false,
            reason: 'Active loan within terms',
            actions: ['maintain_repayments']
        };
    }

    // ============================================
    // DISPUTE RESOLUTION METHODS
    // ============================================

    validateDispute(disputeData) {
        const errors = [];
        const requiredEvidence = this.disputeRules.evidence.required;
        
        // Basic validation
        if (!disputeData.parties || disputeData.parties.length < 2) {
            errors.push('Dispute must involve at least two parties');
        }
        
        if (!disputeData.description || disputeData.description.length < 20) {
            errors.push('Dispute description must be at least 20 characters');
        }
        
        // Evidence validation
        if (!disputeData.evidence || disputeData.evidence.length === 0) {
            errors.push('Evidence is required for dispute');
        } else {
            for (const evidenceType of requiredEvidence) {
                const hasEvidence = disputeData.evidence.some(e => e.type === evidenceType);
                if (!hasEvidence) {
                    errors.push(`Missing required evidence: ${evidenceType}`);
                }
            }
        }
        
        // Amount validation if applicable
        if (disputeData.amount && !this.currency.isValidAmount(disputeData.amount)) {
            errors.push('Invalid dispute amount');
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            escalationPath: this.disputeRules.escalation,
            timeframes: this.disputeRules.timeframes
        };
    }

    escalateDispute(dispute, currentLevel) {
        const escalationLevels = Object.keys(this.disputeRules.escalation);
        const currentIndex = escalationLevels.indexOf(currentLevel);
        
        if (currentIndex === -1 || currentIndex >= escalationLevels.length - 1) {
            return {
                canEscalate: false,
                reason: 'Maximum escalation level reached',
                currentLevel,
                finalResolution: 'platform_admin_decision'
            };
        }
        
        const nextLevel = escalationLevels[currentIndex + 1];
        const resolutionBody = this.disputeRules.escalation[nextLevel];
        
        return {
            canEscalate: true,
            currentLevel,
            nextLevel,
            resolutionBody,
            timeframe: this.disputeRules.timeframes[`${nextLevel}Resolution`] || '14_days',
            actions: ['submit_additional_evidence', 'await_decision']
        };
    }

    // ============================================
    // SECURITY AND COMPLIANCE METHODS
    // ============================================

    validatePassword(password) {
        const errors = [];
        
        if (password.length < 8 || password.length > 12) {
            errors.push('Password must be 8-12 characters');
        }
        
        if (!/[a-z]/.test(password)) {
            errors.push('Password must contain lowercase letters');
        }
        
        if (!/[A-Z]/.test(password)) {
            errors.push('Password must contain uppercase letters');
        }
        
        if (!/[0-9]/.test(password)) {
            errors.push('Password must contain numbers');
        }
        
        if (!/[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password)) {
            errors.push('Password must contain special characters');
        }
        
        return {
            isValid: errors.length === 0,
            errors,
            strength: this._calculatePasswordStrength(password)
        };
    }

    _calculatePasswordStrength(password) {
        let strength = 0;
        
        if (password.length >= 8) strength++;
        if (password.length >= 10) strength++;
        if (/[a-z]/.test(password)) strength++;
        if (/[A-Z]/.test(password)) strength++;
        if (/[0-9]/.test(password)) strength++;
        if (/[^A-Za-z0-9]/.test(password)) strength++;
        
        const strengths = ['Very Weak', 'Weak', 'Fair', 'Good', 'Strong', 'Very Strong'];
        return strengths[Math.min(strength, strengths.length - 1)];
    }

    detectSuspiciousActivity(activity) {
        const warnings = [];
        
        // Multiple login attempts
        if (activity.failedLogins > 5) {
            warnings.push({
                type: 'MULTIPLE_FAILED_LOGINS',
                severity: 'HIGH',
                action: 'temporary_lockout',
                message: 'Multiple failed login attempts detected'
            });
        }
        
        // Unusual location
        if (activity.previousLocation && activity.currentLocation) {
            const distance = this._calculateDistance(
                activity.previousLocation,
                activity.currentLocation
            );
            
            if (distance > 500 && activity.timeDifference < 3600000) { // 500km in 1 hour
                warnings.push({
                    type: 'UNUSUAL_LOCATION',
                    severity: 'MEDIUM',
                    action: 'verify_location',
                    message: 'Login from unusual location detected'
                });
            }
        }
        
        // Large transaction
        if (activity.transactionAmount > 10000000) { // 10 million UGX
            warnings.push({
                type: 'LARGE_TRANSACTION',
                severity: 'MEDIUM',
                action: 'additional_verification',
                message: 'Large transaction requires verification'
            });
        }
        
        return {
            hasSuspiciousActivity: warnings.length > 0,
            warnings,
            recommendedActions: warnings.map(w => w.action)
        };
    }

    _calculateDistance(loc1, loc2) {
        // Simple distance calculation (Haversine formula simplified)
        const R = 6371; // Earth's radius in km
        const lat1 = loc1.latitude * Math.PI / 180;
        const lat2 = loc2.latitude * Math.PI / 180;
        const dLat = (loc2.latitude - loc1.latitude) * Math.PI / 180;
        const dLon = (loc2.longitude - loc1.longitude) * Math.PI / 180;
        
        const a = Math.sin(dLat/2) * Math.sin(dLat/2) +
                  Math.cos(lat1) * Math.cos(lat2) *
                  Math.sin(dLon/2) * Math.sin(dLon/2);
        const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
        
        return R * c;
    }

    // ============================================
    // UTILITY METHODS
    // ============================================

    getRulesSummary() {
        return {
            country: this.countryName,
            hierarchy: this.hierarchy,
            legal: {
                regulatoryBody: this.legalRules.regulatoryBody,
                license: this.legalRules.licenseNumber,
                maxInterest: `${this.legalRules.maxInterestRate * 100}%`
            },
            groupRules: {
                minMembers: this.groupRules.creation.minAge,
                maxMembers: this.hierarchy.groups.maxMembers,
                maxGroupsPerUser: this.hierarchy.groups.maxGroupsPerUser
            },
            lenderRules: {
                minAge: this.lenderRules.eligibility.minAge,
                subscriptionRequired: this.lenderRules.subscription.mandatory
            },
            borrowerRules: {
                minAge: this.borrowerRules.eligibility.minAge,
                repaymentPeriod: `${this.borrowerRules.repayment.period} days`,
                interest: `${this.borrowerRules.repayment.interest * 100}%`
            },
            reputation: {
                ratingSystem: this.reputationRules.ratingSystem.scale,
                blacklistThreshold: `${this.reputationRules.blacklist.trigger} days`
            }
        };
    }

    exportRulesForUI() {
        return {
            country: this.countryName,
            currency: this.currency.config.currencyCode,
            rules: {
                // Group rules
                group: {
                    minMembers: this.hierarchy.groups.minMembers,
                    maxMembers: this.hierarchy.groups.maxMembers,
                    types: this.hierarchy.groups.types,
                    invitationOnly: this.hierarchy.groups.invitationOnly
                },
                
                // Lender rules
                lender: {
                    subscriptionRequired: this.lenderRules.subscription.mandatory,
                    expiry: this.lenderRules.subscription.expiryDate,
                    tiers: Object.keys(this.currency.config.subscriptionTiers).map(key => ({
                        name: this.currency.config.subscriptionTiers[key].name,
                        weeklyLimit: this.currency.format(this.currency.config.subscriptionTiers[key].weeklyLimit)
                    }))
                },
                
                // Borrower rules
                borrower: {
                    noSubscription: this.borrowerRules.eligibility.noSubscription,
                    repaymentPeriod: this.borrowerRules.repayment.period,
                    interest: `${this.borrowerRules.repayment.interest * 100}%`,
                    penalty: `${this.borrowerRules.repayment.penalty.split('_')[0]}% daily after 7 days`
                },
                
                // Legal
                legal: {
                    disclosures: this.legalRules.disclosures.slice(0, 3),
                    prohibited: this.legalRules.prohibited.slice(0, 3)
                }
            }
        };
    }
}

// ============================================
// ERROR CLASSES
// ============================================

export class UgandaRulesError extends Error {
    constructor(message, code, details = {}) {
        super(message);
        this.name = 'UgandaRulesError';
        this.code = code;
        this.country = 'UG';
        this.timestamp = new Date().toISOString();
        this.details = details;
    }
}

export class HierarchyViolationError extends UgandaRulesError {
    constructor(violation, entity) {
        super(`Hierarchy violation: ${violation}`, 'HIERARCHY_VIOLATION', { entity });
        this.violation = violation;
        this.entity = entity;
    }
}

export class SubscriptionViolationError extends UgandaRulesError {
    constructor(reason, lender) {
        super(`Subscription violation: ${reason}`, 'SUBSCRIPTION_VIOLATION', { lender });
        this.reason = reason;
        this.lender = lender;
    }
}

export class BlacklistViolationError extends UgandaRulesError {
    constructor(borrower, reason) {
        super(`Blacklist violation: ${reason}`, 'BLACKLIST_VIOLATION', { borrower });
        this.borrower = borrower;
        this.reason = reason;
    }
}

// ============================================
// EXPORT AND SINGLETON PATTERN
// ============================================

let ugandaRulesInstance = null;

export function getUgandaRules() {
    if (!ugandaRulesInstance) {
        ugandaRulesInstance = new UgandaRules();
    }
    return ugandaRulesInstance;
}

export default UgandaRules;

// ============================================
// HELPER FUNCTIONS
// ============================================

export function validateUgandaGroup(groupData) {
    const rules = getUgandaRules();
    return rules.validateGroupCreation(groupData.creator, groupData);
}

export function validateUgandaLender(lenderData) {
    const rules = getUgandaRules();
    return rules.validateLenderRegistration(lenderData);
}

export function validateUgandaBorrower(borrowerData) {
    const rules = getUgandaRules();
    return rules.validateBorrowerRegistration(borrowerData);
}

export function calculateUgandaRating(repaymentHistory) {
    const rules = getUgandaRules();
    return rules.calculateBorrowerRating(repaymentHistory);
}

// ============================================
// INTEGRATION WITH GLOBAL SYSTEM
// ============================================

if (typeof window !== 'undefined') {
    window.MPesewa = window.MPesewa || {};
    window.MPesewa.rules = window.MPesewa.rules || {};
    window.MPesewa.rules.UG = getUgandaRules();
}

// ============================================
// TEST UTILITIES
// ============================================

export function testUgandaRules() {
    const rules = getUgandaRules();
    
    console.log('=== Uganda Rules Module Test ===');
    console.log(`Country: ${rules.countryName}`);
    console.log(`Hierarchy: ${rules.hierarchy.global} → ${rules.hierarchy.country}`);
    
    // Test hierarchy
    console.log('\nHierarchy Test:');
    const hierarchyTest = rules.validateHierarchy({
        type: 'group',
        country: 'UG',
        members: ['user1', 'user2', 'user3', 'user4', 'user5']
    });
    console.log(`Valid group: ${hierarchyTest.isValid}`);
    
    // Test group creation
    console.log('\nGroup Creation Test:');
    const groupTest = rules.validateGroupCreation(
        { age: 25, nationalId: 'CM1234567', phoneVerified: true },
        { name: 'Test Group', type: 'Family', members: [] }
    );
    console.log(`Can create group: ${groupTest.canCreate}`);
    
    // Test lender validation
    console.log('\nLender Validation Test:');
    const lenderTest = rules.validateLenderRegistration({
        age: 22,
        nationalId: 'CM1234567',
        phoneVerified: true,
        locationVerified: true,
        subscriptionTier: 'basic',
        categories: ['transport', 'food']
    });
    console.log(`Valid lender: ${lenderTest.isValid}`);
    
    // Test borrower validation
    console.log('\nBorrower Validation Test:');
    const borrowerTest = rules.validateBorrowerRegistration({
        age: 20,
        nationalId: 'CM1234567',
        phoneNumber: '+256700123456',
        location: 'Kampala',
        blacklisted: false
    });
    console.log(`Valid borrower: ${borrowerTest.isValid}`);
    
    // Test password validation
    console.log('\nPassword Validation Test:');
    const passwordTest = rules.validatePassword('Test@1234');
    console.log(`Valid password: ${passwordTest.isValid}, Strength: ${passwordTest.strength}`);
    
    return {
        summary: rules.getRulesSummary(),
        testsPassed: true,
        hierarchy: rules.hierarchy
    };
}

// ============================================
// COMPLIANCE CHECK FUNCTION
// ============================================

export function performComplianceCheck(entity, operation) {
    const rules = getUgandaRules();
    const checks = [];
    
    // Check country isolation
    checks.push({
        check: 'COUNTRY_ISOLATION',
        passed: entity.country === 'UG',
        message: entity.country === 'UG' ? 
            'Country isolation maintained' : 
            'Cross-country operation attempted'
    });
    
    // Check hierarchy compliance
    const hierarchyCheck = rules.validateHierarchy(entity);
    checks.push({
        check: 'HIERARCHY_COMPLIANCE',
        passed: hierarchyCheck.isValid,
        message: hierarchyCheck.isValid ? 
            'Hierarchy rules followed' : 
            hierarchyCheck.errors[0]
    });
    
    // Check legal compliance
    checks.push({
        check: 'LEGAL_COMPLIANCE',
        passed: true, // Assume passed, actual check would be more complex
        message: 'Compliant with Uganda regulations'
    });
    
    // Check subscription if lender
    if (entity.type === 'lender' && operation === 'lend') {
        const subscriptionCheck = rules.validateLenderSubscription(entity, entity.subscription);
        checks.push({
            check: 'SUBSCRIPTION_VALID',
            passed: subscriptionCheck.canLend,
            message: subscriptionCheck.canLend ? 
                'Active subscription' : 
                'Subscription expired or invalid'
        });
    }
    
    const allPassed = checks.every(c => c.passed);
    
    return {
        compliant: allPassed,
        checks,
        entityType: entity.type,
        operation,
        timestamp: new Date().toISOString()
    };
}

// ============================================
// METADATA AND VERSIONING
// ============================================

export const METADATA = {
    version: '1.0.0',
    country: 'Uganda',
    lastUpdated: '2024-01-24',
    strictEnforcement: [
        'HIERARCHY_STRICT',
        'COUNTRY_ISOLATION',
        'SUBSCRIPTION_MANDATORY',
        'BLACKLIST_ENFORCEMENT',
        'LEGAL_COMPLIANCE'
    ],
    hierarchy: {
        level1: 'Global (M-Pesewa)',
        level2: 'Country (UG)',
        level3: 'Groups (unlimited)',
        level4: 'Lenders (min 5, max 1000 per group)',
        level5: 'Borrowers/Ledgers (unlimited per lender)'
    },
    changelog: [
        '2024-01-24: Initial release with strict hierarchy enforcement',
        '2024-01-24: Added comprehensive validation methods',
        '2024-01-24: Integrated with currency module'
    ]
};